// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSlds
{
        public const string achievement_60_waves = "CgkIi5i95v0fEAIQEg"; // <GPGSID>
        public const string achievement_full_endurance = "CgkIi5i95v0fEAIQDA"; // <GPGSID>
        public const string achievement_1000_pts = "CgkIi5i95v0fEAIQBw"; // <GPGSID>
        public const string achievement_new_skin = "CgkIi5i95v0fEAIQAg"; // <GPGSID>
        public const string achievement_10_waves = "CgkIi5i95v0fEAIQDQ"; // <GPGSID>
        public const string achievement_2000_pts = "CgkIi5i95v0fEAIQCA"; // <GPGSID>
        public const string achievement_20_waves = "CgkIi5i95v0fEAIQDg"; // <GPGSID>
        public const string achievement_10000_pts = "CgkIi5i95v0fEAIQCg"; // <GPGSID>
        public const string achievement_full_damage = "CgkIi5i95v0fEAIQCw"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIi5i95v0fEAIQFw"; // <GPGSID>
        public const string achievement_40_waves = "CgkIi5i95v0fEAIQEA"; // <GPGSID>
        public const string achievement_80_waves = "CgkIi5i95v0fEAIQFg"; // <GPGSID>
        public const string achievement_500_pts = "CgkIi5i95v0fEAIQAw"; // <GPGSID>
        public const string achievement_life_upgrade = "CgkIi5i95v0fEAIQBQ"; // <GPGSID>
        public const string achievement_50_waves = "CgkIi5i95v0fEAIQEQ"; // <GPGSID>
        public const string achievement_sword_upgrade = "CgkIi5i95v0fEAIQBA"; // <GPGSID>
        public const string achievement_70_waves = "CgkIi5i95v0fEAIQFA"; // <GPGSID>
        public const string achievement_30_waves = "CgkIi5i95v0fEAIQDw"; // <GPGSID>
        public const string leaderboard_high_score_beta = "CgkIi5i95v0fEAIQAQ"; // <GPGSID>
        public const string achievement_30000_pts = "CgkIi5i95v0fEAIQFQ"; // <GPGSID>
        public const string achievement_20000_pts = "CgkIi5i95v0fEAIQEw"; // <GPGSID>
        public const string achievement_5000_pts = "CgkIi5i95v0fEAIQCQ"; // <GPGSID>

}

